#! /bin/sh

set -e

if ! mountpoint /boot/efi; then
        mount /boot/efi
fi

test -f /etc/kutils/kutils.conf && . /etc/kutils/kutils.conf
test -z "${BOOTENTRY}" && BOOTENTRY=gentoo

if ! test -d "/boot/efi/EFI/${BOOTENTRY}"; then
        echo "/boot/efi/EFI/${BOOTENTRY} does not exist or is not a directory" >&2
        exit 1
fi

efibootmgr -c -L "${BOOTENTRY}" -d /dev/nvme0n1 -l '\EFI\${BOOTENTRY}\vmlinuz-${BOOTENTRY}.efi'  -u 'ro quiet splash systemd.show_status=0 loglevel=3 udev.log_level=3 initrd=EFI\${BOOTENTRY}\initramfs-${BOOTENTRY}.img'
