#! /bin/sh

set -e

if ! mountpoint /boot/efi; then
	mount /boot/efi
fi

test -f /etc/kutils/kutils.conf && . /etc/kutils/kutils.conf
test -z "${BOOTENTRY}" && BOOTENTRY=gentoo

if ! test -d "/boot/efi/EFI/${BOOTENTRY}"; then
	echo "/boot/efi/EFI/${BOOTENTRY} does not exist or is not a directory" >&2
	exit 1
fi

cd /usr/src/linux
export KCFLAGS="-march=native -O2 -pipe -fomit-frame-pointer -fdevirtualize-at-ltrans -fgcse-after-reload"

make KCFLAGS="${KCFLAGS}" -j"$(nproc)"
make KCFLAGS="${KCFLAGS}" bzImage 
make KCFLAGS="${KCFLAGS}" modules 
make KCFLAGS="${KCFLAGS}" modules_install 

chgrp -HR portage /usr/src/linux/ 
chgrp -R portage /lib/modules/*

if test -n "${KMAKE_EMERGE}"; then
	emerge -1 ${KMAKE_EMERGE}
fi

cp arch/x86_64/boot/bzImage "/boot/efi/EFI/${BOOTENTRY}/vmlinuz-${BOOTENTRY}.efi"

if test -f "/boot/efi/EFI/${BOOTENTRY}/config"; then
	cp "/boot/efi/EFI/${BOOTENTRY}/config" "/boot/efi/EFI/${BOOTENTRY}/config.old"
fi

cp .config "/boot/efi/EFI/${BOOTENTRY}/config"

