#! /bin/sh

set -eu


echo '0' > '/proc/sys/kernel/nmi_watchdog'
echo 1500 > /proc/sys/vm/dirty_writeback_centisecs

test -x /etc/kutils/start_misc && /etc/kutils/start_misc

echo 'auto' > '/sys/bus/pci/devices/0000:05:00.0/power/control';

echo 70000 | tee /sys/class/hwmon/hwmon2/pwm*_auto_point3_temp
echo 50000 | tee /sys/class/hwmon/hwmon2/pwm*_auto_point2_temp
echo 32500 | tee /sys/class/hwmon/hwmon2/pwm*_auto_point1_temp

#/usr/local/sbin/disable-usb-wakeup.sh
